import ContactUs from "../components/ContactUs/ContactUsPage";
export const metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};
export default function ContactUsPage() {
  return <ContactUs />;
}
