import ServicesPage from "../components/Food Services/ServicesPage";
export const metadata = {
  title: "Food Services",
  description: "Generated by create next app",
  alternates: { canonical: "https://www.foodtechnologylabs.com/food-services" },
};
export default function Services() {
  return <ServicesPage />;
}
