import ToolsPage from "../components/ToolsPage/ToolsPage";

export const metadata = {
  title: "Food Tools",
  description: "Generated by create next app",
};
export default function Tools() {
  return <ToolsPage />;
}
